id: d0dc3542-2d0a-4184-8ec0-f0ab876bf752
Function:
  Title: Parser for ExchangeEnvironmentList
  Version: '1.0.0'
  LastUpdated: '2023-08-22'
Category: Microsoft Sentinel Parser
FunctionName: ExchangeEnvironmentList
FunctionAlias: ExchangeEnvironmentList
FunctionQuery: |
    let _target = iff(isnull(Target) or isempty(Target),"On-Premises",Target);
    let ScalarbaseRequest = union isfuzzy=true withsource=TableName ESIAPIExchange*,ESIExchange*
        | extend Source = iff (TableName contains "Online", "Online", "On-Premises")
        | where _target == 'All' or Source == _target;
    // Base Request
    ScalarbaseRequest | summarize by ESIEnvironment_s | project-rename ESIEnvironment = ESIEnvironment_s