name: Add Label on Pull Request

on:  
  workflow_call:
    inputs:
      labelName:
        required: true
        type: string

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  addLabelOnPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@29423367f079522048aa7c63f671593b0556ffd5
        name: Add Label To Pull Request
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            $labelName = "${{ inputs.labelName }}"
            console.log('PR Number : ' + context.issue.number + ', LabelName ' + $labelName)
            github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [$labelName]
            })